### PR TITLE
Unify functions

### PR DESCRIPTION
**Pull request by LeoMNC**
I found I was having trouble getting the spreadr() function to interact with matrices. This version lets spreadr() take named adjacency matrices as inputs.
[spreadr_matrix_friendly.zip](https://github.com/csqsiew/spreadr/files/6484005/spreadr_matrix_friendly.zip)

### CODE REVIEW

**Comment by ning-y** [comment]
Hi @LeoMNC, thank you for your contribution. We can't see your change, however, because this pull request seems to have been created to pull our older version of spreadr (from the unify-function branch) into the main and current version of spreadr (also called the master branch):

image

To remedy this, you can edit this pull request (top-right of the page),

image

and change the "compare" branch to the one in which you made your change.

image

**You can also try out the newest version of spreadr (v0.2.0), and see if that fixes your problem.** Check your current version of spreadr using [`packageVersion("spreadr")`](https://stackoverflow.com/a/11103209/6910451). Update spreadr using `install.packages("spreadr")`.

**Comment by LeoMNC** [comment]
Thanks for the feedback. I'm new to GitHub and still learning its structure. Hopefully this works now.

**Comment by ning-y** [comment]
@LeoMNC I see now that you have attached your changes in the ZIP file. The new version of spreadr I cited above, released just last week, should work with adjacency matrices as input. May I trouble you for an example of a matrix you had trouble getting spreadr to work with?

**Comment by LeoMNC** [comment]
@ning-y I see the issue has been fixed. Thank you all!

**Comment by ning-y** [comment]
@LeoMNC Glad to hear it, happy trails!

**Pull request closed without merging**
